name: Create Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: package-version
      run: echo "PACKAGE_VERSION=$(grep version package.json | awk -F \" '{print $4}')" >> $GITHUB_ENV
        
    - name: npm install, build
      run: |
        npm install
        npm run build
        
    - name: Copy all necessary files
      run: |
        mkdir release
        mkdir release/siem
        cp -R build/* release/siem
        cp -r configs release/configs
        cp package-lock.json release/package-lock.json
        cp package.json release/package.json
        cp .gitignore release/.gitignore
        cp LICENSE release/LICENSE
        cp setup.sh release/setup.sh

    
    - name: Publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: release
        FOLDER: release
        GITHUB_TOKEN: ${{ secrets.PUBLISH_ACCESS_TOKEN }}
        MESSAGE: "Build: ({sha}) {msg}"